package com.example.collectorconnector.util

object Constants {
    val MESSAGE_TYPE_TEXT = "TEXT"
    val MESSAGE_TYPE_IMAGE = "IMAGE"
    val MESSAGE_TYPE_TRADE = "TRADE"

    val TRADE_STATUS_OPEN = "OPEN"
    val TRADE_STATUS_CANCELED = "CANCELED"
    val TRADE_STATUS_ACCEPTED = "ACCEPTED"
    val TRADE_STATUS_REJECTED = "REJECTED"

    val REQUEST_LOCATION_PERMISSION = 1
    val PICK_IMAGE_REQUEST = 2
    val ONE_HUNDRED_MEGABYTE: Long = 1024 * 1024 * 100
}